### ISSUE TITLE
Default config file used, when implementing non-default config file as advised in README

### ISSUE THREAD

**Issue by spletts** [Ohervet/Bjet_MCMC#1]
The README.md states:
> The default configuration file is mcmc_config.txt in the main directory. If you would like to use a different file, in blazar_run_mcmc.py in main, replace config_file=None and/or directory=None with the location of the config file and/or the desired directory for results.

In blazar_run_mcmc.py in main I set:
`mcmc(config_file='nondefault_mcmc_config.txt')`. 

In my case, the `data_file` in the _default_ config file mcmc_config.txt no longer exists (I `mv`'d it), and so I get an error (`FileNotFoundError`) that traces to blazar_plots.py in `plot_data()` because the `data_file` that is being looked for here is from from _default_ config file:
```python
configs = blazar_utils.read_configs()
data = blazar_utils.read_data(configs["data_file"], instrument=True)
```

Is the non-default config filename propagated through the code in **all** the relevant places?

In blazar_mcmc.py one of the first lines is
`configs = blazar_utils.read_configs()` which will use the default for `read_configs` i.e. `config_file="mcmc_config.txt"`.

There are other instances of `blazar_utils.read_configs()` in blazar_report.py.

**Comment by Ohervet** [comment]
I have updated how to use a customized path/name for your config file. Now you can enter the absolute path of your configuration file as an argument when running `blazar_run_mcmc.py`, such as  `python blazar_run_mcmc.py /home/myconfigfile.txt` 
If you run it without argument, it will use the default `config.txt`
